# Generated by Django 5.0.7 on 2024-08-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist_watchlist_unique_user_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.FloatField(),
        ),
    ]
