# Generated by Django 5.0.7 on 2024-08-13 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('toys', 'Toys & Games'), ('sports', 'Sports & Outdoors'), ('books', 'Books & Media'), ('vehicles', 'Vehicles'), ('art', 'Art')], default='art', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='listing',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.categorie'),
        ),
    ]
